version: '3.8'
services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    container_name: dash-app
    volumes:
      - .:/app
    networks:
      - stack_backend

networks:
  stack_backend:
    external: true
