version: '3.8'

services:
  dash-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash-app
    ports:
      - "8050:8050"
    volumes:
      - ./dash-app:/app
    environment:
      - DASH_DEBUG=true
    networks:
      - dash_backend

networks:
  dash_backend:
    driver: bridge
