services:
  dash-app:
    build: .
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - stack_backend

networks:
  stack_backend:
    external: true
